version: "3.8"
services:
  master:
    build: .
    container_name: master
    stdin_open: true
    tty: true
    hostname: master
  client1:
    build:
      context: .
      dockerfile: client_container
    container_name: client_1
    stdin_open: true
    tty: true
    hostname: client1
volumes:
  keyshare: